_schema: _schema
timezone: Etc/UTC
collections:
  - name: stranice
    label: stranice
    path: ''
    files:
      - file: index.html
        label: Početna stranica
  - name: ''
    label: ''
    path: ''
    files:
      - file: ''
        label: ''
